services:
  backend:
    image: ghcr.io/erwol/mediaflow-backend:latest
    restart: unless-stopped
    volumes:
      - ${MOVIES_DIR}:${MOVIES_DIR}
      - ${TVSHOWS_DIR}:${TVSHOWS_DIR}
    environment:
      - MOVIES_DIR=${MOVIES_DIR}
      - TVSHOWS_DIR=${TVSHOWS_DIR}

  frontend:
    image: ghcr.io/erwol/mediaflow-frontend:latest
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3005}:80"
    depends_on:
      - backend
